name: awesome-action
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  this_is_safe:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Print PR title"
        if: github.event_name == 'pull_request'
        #aqui tinha injection, ver na base se der merda

      - name: "Do something awesome"
        uses: super-safe/nothing-to-see-here-action@v1.2.3
